### ISSUE TITLE
[Provider] Azure Inference API

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#491] opened 2024-08-01 19:29 UTC
https://techcommunity.microsoft.com/t5/ai-machine-learning-blog/introducing-the-azure-ai-model-inference-api/ba-p/4144292

**Comment by narengogi** [comment] 2024-08-21 09:59
duplicate of https://github.com/Portkey-AI/gateway/issues/492

**Closed as completed** 2024-08-29 16:25 UTC
Labels: triage, provider
